# fly.toml app configuration file generated for patient-frost-274 on 2023-06-11T14:59:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "patient-frost-274"
primary_region = "waw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
